site_name: Amazon Quick Suite Knowledge Hub
theme:
  name: material
  custom_dir: static/overrides
  logo: quicksuite.png
  favicon: quicksuite.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: white
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: black
    toggle:
      icon: material/weather-sunny
      name: "Switch to light mode"
docs_dir: docs
exclude_docs: |
  node_modules/
  **/node_modules/**
  use-cases/*/cdk/
  use-cases/*/infrastructure/
  use-cases/*/fe/
  use-cases/*/tools/
  !use-cases/*/images/
  !use-cases/*/README.md
  !use-cases/*/LICENSE
extra_css:
  - stylesheets/extra.css
extra:
  static_path: ../static
plugins:
  - search
  - macros
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - fenced_code
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      url_download: True
      url_request_headers:
nav:
  - üè† Home: index.md
  - üìö Guidance:
    - How to..: guidance/how-to.md
  - üîó Integration:
    - Knowledge Base: integration/knowledge-base.md
    - Actions: integration/actions.md
  - üí° Use Cases:
    - Overview: use-cases/index.md
    - Actuarial Analysis Solution: use-cases/actuarial-analysis-solution/README.md
    - Bedrock KB Retrieval MCP: use-cases/bedrock-kb-retrieval-mcp/README.md
    - Quick Chat Agent Embedding Demo: use-cases/quick-chat-agent-embedding-demo/README.md
    - Redshift Data Query MCP: use-cases/redshift-data-query-mcp/README.md
  - ‚ù§Ô∏è How To Contribute: HOW-TO-CONTRIBUTE.md
repo_url: https://github.com/aws-samples/sample-amazon-quick-suite-knowledge-hub
edit_uri: edit/main/docs/
