site_name: Amazon Quick Suite Knowledge Hub
theme:
  name: material
  custom_dir: static/overrides
  logo: quicksuite.png
  favicon: quicksuite.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: white
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: black
    toggle:
      icon: material/weather-sunny
      name: "Switch to light mode"
docs_dir: docs
exclude_docs: |
  node_modules/
  **/node_modules/**
  use-cases/*/cdk/
  use-cases/*/infrastructure/
  use-cases/*/fe/
  use-cases/*/tools/
  integration/actions/MCP/*/cdk/
  integration/actions/MCP/*/tools/
  !use-cases/*/images/
  !use-cases/*/README.md
  !use-cases/*/LICENSE
  !integration/actions/MCP/*/images/
  !integration/actions/MCP/*/README.md
  !integration/actions/MCP/*/LICENSE
extra_css:
  - stylesheets/extra.css
extra:
  static_path: ../static
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - fenced_code
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      url_download: True
      url_request_headers:
nav:
  - Home: index.md
  - Infrastructure as a Code:
    - Terraform: infrastructure as code/Terraform/README.md
  - Manage Quick Suite:
    - Identity: manage quick/Identity.md
    - Observability: manage quick/Observability.md
    - Customization: manage quick/Customization.md
    - Security:
      - Guardrails: manage quick/Security/Guardrails.md
  - Integration:
    - Knowledge Base:
      - Confluence Cloud: integration/knowledge base/confluence-cloud-knowledge-only-setup-guide/README.md
    - Actions: 
      - MCP:
        - Amazon Bedrock KB Retrieval MCP: integration/actions/MCP/bedrock-kb-retrieval-mcp/README.md
        - Amazon Redshift Data Query MCP: integration/actions/MCP/redshift-data-query-mcp/README.md
        - Amazon Gateway AgentCore S3 MCP: integration/actions/MCP/gateway-agentcore-s3-crud-mcp/README.md
      - Asana: integration/actions/asana-action-setup-guide/README.md
      - Box: integration/actions/box-action-setup-guide/README.md
      - Confluence Cloud: integration/actions/confluence-cloud-knowledge-action-setup-guide/README.md
      - Jira Cloud: integration/actions/jira-cloud-action-setup-guide/README.md
      - MS Outlook: integration/actions/ms-outlook-action-setup-guide/README.md
      - MS SharePoint: integration/actions/ms-sharepoint-action-setup-guide/README.md
      - MS Teams: integration/actions/ms-teams-action-setup-guide/README.md
      - PagerDuty: integration/actions/pagerduty-action-setup-guide/README.md
      - Salesforce: integration/actions/salesforce-action-setup-guide/README.md
      - ServiceNow: integration/actions/servicenow-action-setup-guide/README.md
      - ServiceNow (2LO): integration/actions/2lo-servicenow-action-setup-guide/README.md
      - Slack: integration/actions/slack-action-setup-guide/README.md
      - Smartsheet: integration/actions/smartsheet-action-setup-guide/README.md
  - Use Cases:
    - Actuarial Analysis Solution: use-cases/actuarial-analysis-solution/README.md
    - Quick Chat Agent Embedding Demo: use-cases/quick-chat-agent-embedding-demo/README.md
  - How To Contribute: HOW-TO-CONTRIBUTE.md
repo_url: https://github.com/aws-samples/sample-amazon-quick-suite-knowledge-hub
edit_uri: edit/main/docs/
